name: Terraform inits
description: Init terraform and check both fmt and validity.
inputs:
  working_dir:
    required: true

defaults:
  run:
    shell: bash

on:
  pull_request_review:
    types: [submitted]
    paths:
      - aws/**
  pull_request:
    paths:
      - aws/**

terraform-init:
  using: "composite"
  runs-on: ubuntu-latest
  steps:
    - name: Terraform fmt
      id: fmt
      working-directory: ${{ working_dir }}
      run: terraform fmt -check -diff -no-color
      continue-on-error: true

    - name: Terraform Init
      id: init
      working-directory: ${{ working_dir }}
      run: terraform init

    - name: Terraform Validate
      id: validate
      working-directory: ${{ working_dir }}
      run: terraform validate -no-color
