name: 'Terraform Plan'

on:
  pull_request:
    paths:
      - aws/**

defaults:
  run:
    shell: bash

jobs:
  diffs:
    name: "Check the changes"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: set-matrix
      run: |
        git fetch origin main
        X=""
        for i in $(git diff --dirstat=files,0 ..FETCH_HEAD|cut -d'%' -f 2|cut -d' ' -f 2|grep aws);do X="$X,\"$i\"";done
        X="${X:1}"
        echo "matrix={\"dir\":[$X]}" >> $GITHUB_OUTPUT

  terraform:
    needs: diffs
    name: "Check, Verify, Plan"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix: ${{fromJson(needs.diffs.outputs.matrix)}}

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Plan
      id: plan
      working-directory: ${{ matrix.dir }}
      run: |
        cat << EOF > backend.tf
        terraform {
          backend "s3" {
            bucket = "deriv-playground-iac-states"
            key    = "${{ matrix.dir }}"
            region = "us-east-1"

            dynamodb_table = "terraform-s3-backend-locking"
          }
        }
        EOF
        terraform init -no-color
        terraform fmt -check -diff -no-color
        terraform validate -no-color
        terraform plan -no-color
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_READONLY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_READONLY }}

    - uses: actions/github-script@v6
      if: always()
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `### Dir: ${{ matrix.dir }}
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          <details><summary>Init, Fmt, Verify, Plan Output</summary>

          \`\`\`\n
          ${{ steps.plan.outputs.stdout }}
          ${{ steps.plan.outputs.stderr }}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

  plan-passed:
    needs: terraform
    name: "Plan passed"
    runs-on: ubuntu-latest

    steps:
    - name: All done
      id: plan-passed
      run: echo "All passed"
