name: 'Terraform Apply'

on:
  pull_request_review:
    types: [submitted]
    paths:
      - aws/**

defaults:
  run:
    shell: bash

jobs:
  diffs:
    name: "Check the changes"
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: set-matrix
      run: |
        git fetch origin main
        X=""
        for i in $(git diff --dirstat=files,0 ..FETCH_HEAD|cut -d'%' -f 2|cut -d' ' -f 2|grep aws)
        do
          X="$X,\"$i\""
          cat << EOF > ${i}/backend.tf
          terraform {
            backend "s3" {
              bucket = "deriv-playground-iac-states"
              key    = "${i}"
              region = "us-east-1"

              dynamodb_table ="terraform-s3-backend-locking"
            }
          }
        EOF
        done
        X="${X:1}"
        echo "matrix={\"dir\":[$X]}" >> $GITHUB_OUTPUT

  terraform-pre-apply-plan:
    if: ${{ github.event.review.state == 'approved' }}
    needs: diffs
    name: "PreApply Plan"
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.diffs.outputs.matrix)}}

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      working-directory: ${{ matrix.dir }}
      run: terraform init -no-color
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_READONLY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_READONLY }}

    - name: Terraform Plan
      id: plan
      working-directory: ${{ matrix.dir }}
      run: terraform plan -no-color
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_READONLY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_READONLY }}



  terraform-apply:
    if: ${{ github.event.review.state == 'approved' }}
    needs: [ "terraform-pre-apply-plan", "diffs" ]
    name: "Apply"
    runs-on: ubuntu-latest
    environment: "playground-apply"
    permissions:
      pull-requests: write
    strategy:
      matrix: ${{fromJson(needs.diffs.outputs.matrix)}}

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Apply
      if: ${{ github.event.review.state == 'approved' }}
      id: apply
      working-directory: ${{ matrix.dir }}
      run: terraform apply  -no-color -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - uses: actions/github-script@v6
      if: always()
      env:
        APPLY: "terraform\n${{ steps.apply.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `### Dir: ${{ matrix.dir }}
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          <details><summary>Initialization Output</summary>

          \`\`\`\n
          ${{ steps.init.outputs.stdout }}
          ${{ steps.init.outputs.stderr }}
          \`\`\`

          </details>

          #### Terraform Apply 📖\`${{ steps.apply.outcome }}\`
          <details><summary>Show Apply</summary>

          \`\`\`\n
          ${process.env.APPLY}
          \`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

  apply-passed:
    needs: terraform-apply
    name: "Apply passed"
    runs-on: ubuntu-latest

    steps:
    - name: All done
      id: apply-passed
      run: echo "All passed"
